# Generated by Django 2.2.12 on 2020-04-25 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='end_reading_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='読了日'),
        ),
    ]
